name: docs

on:
  push:
    branches: [ master ]
    #paths: 'myfolder/*/README.md'

jobs:

  copy_source:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@master
    - name: Copy source
      run: |
          cp "source.js" "bookmark.js"
          
    - uses: stefanzweifel/git-auto-commit-action@v4
      #with:
      #  github_token: ${{ secrets.IDM2BIBLATEX_SECRET }}
