name: Build bookmark.js

on:
  push:
    branches: [ master ]
    #paths: 'myfolder/*/README.md'

jobs:

  build_bookmark:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Copy source
      run: |
          cp "source.js" "bookmark.js"
        
    - name: Search and replace
      run: |
        sed -i 's/a/AAAAAAA/g' bookmark.js
      #uses: jafin/gha-search-replace@0.2-alpha
      #with:
      #  include: bookmark.js
      #  search: 'a'
      #  replace: 'AAAAAAAAAA'
        
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Copy `source.js`

    

    
