name: create bookmark file
on: [push]
jobs:

  copy:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "source.js"
        target: "bookmark.js"


