name: Build bookmark.js

on:
  push:
    branches: [ master ]

jobs:

  build_bookmark:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Copy source
      run: |
          cp "source.js" "bookmark.js"
        
    - name: Search and replace newlines
      run: |
        tr -d '\n' < bookmark.js > bookmark.js
        
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Copy `source.js`

    

    
