name: create bookmark file
on: [push]
jobs:

  copy:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: liquibase-github-actions/init-copy@v4.18.0
      with:
        source: "source.js"       # Source directory where the project files will be copied from string
        target: "bookmark2.js"    # Path to the directory where the project files will be created string
